name: 'web_ap'
mode: 'dev'
port: 9000
version: '1.0.0'
start_time: '2023-03-07'
machined_id: 1
lang: 'en' # zh en

log:
  level: 'debug'
  filename: 'web_app.log'
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: '127.0.0.1'
  port: 3306
  user: 'root'
  password: '123456'
  dbname: 'db_test'
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: '127.0.0.1'
  port: 6379
  password: ''
  db: 0
  pool_size: 100
